<?php
/**
 * @file
 * shop_taxonomy.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function shop_taxonomy_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'BRAND',
    'description' => 'Brand Awarenes',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '00588eff-daf5-46a6-8409-53ca55c01793',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EN',
    'description' => 'Engaging Networks',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '00ee4940-5251-40d8-ac49-b3a8352221fe',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'MGM',
    'description' => 'Member get Member promotion',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0838de2b-9c7f-4aaf-a0df-12ec7cb48813',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NA',
    'description' => 'Not Applicable',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0843a517-837c-4ceb-8620-5f487be2d109',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CYCA',
    'description' => 'cycle active',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0987e8e7-3a0a-4a13-ad3d-81f6ff4481b1',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'ROB',
    'description' => 'Recommended - Other Business',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0b66fa41-6f2c-470c-881f-c4751941e6af',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NKIN',
    'description' => 'Next of Kin',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0e52260f-ac26-488e-82bf-d03e23d8ccdd',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CDG',
    'description' => 'Cycle Developement',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1096017a-0b9a-436d-b060-2c549f096651',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'ETC',
    'description' => 'Bike Etc mag',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '10b1e860-9ce5-4fe6-9d0e-9e0a952108e1',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'SOUC01',
    'description' => 'Plymouth CC',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '10cc3db8-3e8d-44db-ac64-014d0e8b9fdf',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'HALMEM',
    'description' => 'Halfords Referral Membership',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '124144f5-e9bf-4636-a160-44aeaee2722b',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'BIKEMILES',
    'description' => 'Please cycle Bike miles website',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '133881a5-154e-4bb7-87fa-084356ba33e1',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EASL04',
    'description' => 'ESE Inclusive Cycling',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '138584c0-a49e-4ff9-88ce-6f4a5290e18f',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RBPO',
    'description' => 'Renewal by Post',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '14d9fe0a-a926-4dd7-a85a-b423785ef202',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'FR',
    'description' => 'Friend or Relative',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '16a577fb-fd87-4b27-a1bc-2f9e05992c68',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'UR',
    'description' => 'Update of Existing Record',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1965e11b-fb64-4455-8dd9-2289a2d9c197',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWR05',
    'description' => 'Community Cycle Clubs WYCA',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1ae17a78-94d2-4e00-b775-e2b0daa090a7',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LG',
    'description' => 'Legacy',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1bd0afb8-c866-4359-9c60-6763d427e011',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EASC01',
    'description' => 'Plymouth CC LSTF',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1e840fff-062f-4add-8040-43b846975c12',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'COMP',
    'description' => 'competition prize',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '1ff4a909-e207-42b7-b9c9-6602386cc486',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EASC03',
    'description' => 'Surrey Community Clubs',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '209bc16a-68d8-4bab-bdad-477e248473d7',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET3004',
    'description' => 'Ret3004',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '257ffa57-76cd-40d5-9676-384db631ce15',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'GA',
    'description' => 'General Awareness',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '28ab553d-19f5-4c84-a97d-c612298afaed',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CTG',
    'description' => 'Cycle Training',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2ea54ca5-d840-4d55-97ec-53a96eee882f',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'MQ',
    'description' => 'Marketing Question',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2ebc1ee3-82a5-4458-a504-c12199fc513d',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LAPSPH',
    'description' => 'Lapse Members Follow Up - Phone',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2ed9fe8f-00eb-4f7a-8033-f96f113861b4',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET2504',
    'description' => 'Ret2504',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '30cb55ab-e1f2-4c8f-99d3-cd7a3664e0f5',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CTON',
    'description' => 'CTC Onroad Training Course',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3234adee-c78b-4464-85d3-2165521ef007',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'WTB',
    'description' => 'what mountain bike - 3 months ',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '372a9578-dd7d-4827-9d3f-b742dae9644a',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWX02',
    'description' => 'Sefton Council',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '381c1521-ca46-47f8-922a-69e5b0f91c23',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'DRAW',
    'description' => 'Grand Draw',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '38e19cba-f54d-4452-930b-359c0b21a1a5',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CAMP',
    'description' => 'Campaigns',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3a73ba0b-a576-48ef-839c-4b590679efe4',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 1512,
    'description' => '15 Months For 12',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3a8f9f04-29c7-4816-b78c-f553b7df5269',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NDIN',
    'description' => 'National Dinner',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3a99c25a-08de-4f85-b5e1-01120813e851',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RIDELONDON',
    'description' => 'Ridelondon event',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3bb9bce1-2418-443e-aa86-4d6b29f7eb51',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'ACIM',
    'description' => 'Affiliated Club Insured Member',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3d37759b-6ac6-4766-8995-e0f250db4921',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'ROULEUR',
    'description' => 'Rouleur Mag 15 4 12',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3ef8680e-1d7e-43ca-be66-49bdd1fdecbe',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LRS',
    'description' => 'Lapsed Reset',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '3fed2ce1-fc1b-46e6-a9e9-966f719aa4e1',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'STRACK',
    'description' => 'Single Track',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4202c101-376b-4e90-b26a-ecb7945bdc64',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'MGMJON',
    'description' => 'Free Dave Walker Mug Jon Snow video',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '43f38526-8ebf-4b8f-9c0b-ffe788260ac7',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 1412,
    'description' => '14 Months For 12',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4434c481-74ba-4215-babc-645de335720a',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'GAID',
    'description' => 'Gift Aid Declaration',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '48706226-ef00-417e-b1ae-34cf75ff9992',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWA03',
    'description' => 'Robertson Trust',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '49ddde2b-1edd-4c2a-a39d-00cd13d9ec1e',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'HAL',
    'description' => 'Halfords',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4ca22e37-17ff-4f41-b7d9-aea923482d19',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'S',
    'description' => 'CTC Staff / Council',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '50e9b8d8-b41d-4173-b7ba-1d1b94b708a6',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'GREATTOUR',
    'description' => 'The Great Tour',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '54d48a33-3548-464c-b9dd-554c65a761b9',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'TIL1512',
    'description' => 'Tilgate extra 3 mths',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '579bc234-af57-47a7-a2bb-f26485425db3',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CDFJM',
    'description' => 'CDF - Justice for Mick',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '57c3023a-7b14-4b59-b1e5-a315369f945a',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CYCLIST',
    'description' => 'cyclist magazine',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '58a2968b-37ee-49ac-92f6-0259ea6619f2',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'BBR16FM',
    'description' => 'BBR 2016 free annual memberships as prizes',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '590252d3-e788-4d65-b3ec-e55e9238edad',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NSPCC',
    'description' => 'NSPCC Tour of England',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5ac8633b-8cd6-470a-ab3a-91808db8d998',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'SCOT1',
    'description' => 'Scottish Cycling magazine',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5b82b2a0-297e-4884-a035-b8932c3b26eb',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EF2017',
    'description' => 'Edinburgh Festival of Cycling 2017 - brochure ad - 14for12',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '5d715dda-6a80-476b-bbc2-20e8250975ab',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'MM2017',
    'description' => 'Mothers Day 2017 Gift Membership - Lezyne saddlebag new join',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '605134ae-f1a1-4538-9fd2-11cb7b2e2dc9',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EASH02',
    'description' => 'Reading LSTF',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6061afc8-293a-4152-bacf-cde268af7015',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RJW',
    'description' => 'RJW staff offer',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '610b0568-e139-418e-8522-164aa37c63b4',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWA13',
    'description' => 'BBR Scotland',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6269be46-69de-40de-8b60-73a40edd7748',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RC',
    'description' => 'Recommendation - Cyclists',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '64043d85-5d28-41e8-94ec-4cd9743f9fe2',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LBS17LIGHT',
    'description' => 'London Bike Show2017 flyer joiner after visit - KTV2 lights',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6600ee7a-f1fa-416d-aae5-e8b3923952d6',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWL01',
    'description' => 'NE Inclusive Cycling',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '67a8fb6e-a4f2-4491-a10c-a84765b3e65a',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'OF',
    'description' => 'outdoor fitness',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6a4a52e7-3295-422e-82b1-8ab6a69dc781',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'READING15',
    'description' => 'Swing tag for Javed for use in the Reading area in 2015',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6ad18eec-7293-4ff4-a281-93b74c67271d',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CTFA',
    'description' => 'CTC First Aid Course',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6d265520-e782-4f6b-b2c8-95140010d1ff',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LCG',
    'description' => 'CTC Local Group (DA)',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '6efce59e-7845-48b7-bbb0-e880ae3739a1',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWW08',
    'description' => 'Amnesty/DFT',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7180f64c-97f8-4fd9-be84-28a874a020a2',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'KNOWN',
    'description' => 'I have known about Cycling UK for a long time',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '725c851a-7672-4582-9d2e-c55a7b00b069',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'BW2016',
    'description' => 'Bike Week 2016 1 year free membership for prizewinners',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '75eec69a-9510-42e4-b023-7d15f2135ddb',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'FTH',
    'description' => 'Fill That Hole',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '761f73c5-2b93-494a-9a1b-07bdec2b3960',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'ST',
    'description' => 'single track mag 3 months free',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '771e534e-d0c9-4c0e-a1ff-cf484d111c51',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'MGM17DW',
    'description' => 'MGM FREE DAVE WALKER MUG',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '772fd4ae-e9a3-4232-96da-34e3c5b338d7',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'THRIVE',
    'description' => 'Thrive Project',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '79c3442a-e4b2-41f3-916c-2df30bdae3d0',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NMPO',
    'description' => 'New Member by Post',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7aa41cea-1119-4101-82b7-090b90612cb3',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'OS',
    'description' => 'Other Source (Add Note)',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7aaa5c27-d1a6-4c78-b09a-c1257269921f',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CDF',
    'description' => 'Cyclists Defence Fund',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7bcef67b-4979-45ef-a50a-85d6b0f84d77',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EBE',
    'description' => 'European Bike Express',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7c8a63fe-af2d-4707-bcdc-b11d0eee32ff',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'SE',
    'description' => 'Search Engine',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7d39a503-7ac7-4bff-9610-4d1551ee3c5a',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CRJ',
    'description' => 'Campaigns - Road Justice',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7db6421f-952d-479c-b295-860038d1e967',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'SCH',
    'description' => 'Scotish Cycle Show',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '7f2e3835-9dee-4ea2-aafa-65cdae8e0bec',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'Five-yearly',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 2,
    'uuid' => '8738ee2e-e6c3-4ea4-a7cf-1804ec338ecb',
    'vocabulary_machine_name' => 'payment_frequencies',
    'field_code' => array(
      'und' => array(
        0 => array(
          'value' => 'F',
          'format' => NULL,
        ),
      ),
    ),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'YHA',
    'description' => 'Youth Hostel Association',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '886a723d-2698-4228-8799-2bf050b321fe',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWA09',
    'description' => 'Bells on bikes',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8a536d74-04fa-4874-abe8-acd716eb2289',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'FAMILY',
    'description' => 'Family £12 upgrade',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8ab1496e-e4a6-47d4-ac60-c48a90def431',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CSH',
    'description' => 'CS Healthcare Journal',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8aea7eff-d5a5-431a-aba9-db51e579a8b0',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EASH05',
    'description' => 'Reading Bike Club',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8b9a3533-5ba1-4b90-b092-feaf69a00dcd',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CYCLE14',
    'description' => 'Cyclemagstudent offer',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8d2f2948-4ad8-4d1b-8e1d-3f91bf212bed',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET2904',
    'description' => 'Ret2904',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '908a786b-bdfb-4f88-b88b-4ffd7f2d29b2',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'POST',
    'description' => 'Created via Post',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '90c34ec2-03ab-4de8-bab1-6da44afda939',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'BEB2017',
    'description' => 'Bike Events 2017 brochure ad_promote 14 for 12 on annual',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9264ee2c-6b33-4df6-952a-85fc746fb201',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWR04',
    'description' => 'WYCA - Access to Bike BBR2',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '938b1687-60f8-41a4-8f5d-3dd463e07adc',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWX09',
    'description' => 'TFGM 2016',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '93f1cc9a-6b9d-41dd-8cd3-63c4e27703c7',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CMAG1',
    'description' => 'Cycle Mag online teaser issue - generic join ad2017 14for12',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '947971b0-ea2f-4375-850a-5e4eabb169b8',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET2604',
    'description' => 'Ret2604',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '95f85889-0cde-4e25-8ab9-9bec3ee4d3a6',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CYCS',
    'description' => 'Cycle Show',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '96153692-47cd-404f-94b1-75103d5bb5eb',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'DWTA',
    'description' => 'I prefer not to give an answer',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '966bbf58-0327-4cbb-85dd-22c4b43f687a',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'OI',
    'description' => 'Over Internet (Web appl\'s)',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '97811f6b-8748-49d7-b29d-9d0d15805810',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'MBR',
    'description' => 'Mountain Bike Rider (magazine)',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '99623799-5cae-4b71-8309-7b7a39434ac7',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET0505',
    'description' => 'RET0505',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9b5a6433-1190-4d6b-b54b-c5219673f80c',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'DIGEST',
    'description' => 'Cycle Digest',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9bde0eed-ee32-472b-b7bb-4baa387ae550',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'PROSPECT',
    'description' => 'Marketing Prospect Contact',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9d7b4f7d-99fd-462a-b790-1861b4c6e437',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'BUS',
    'description' => 'CTC Business Contact',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9d83e929-a52d-4af8-81cc-17d83098f6ed',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RIDELON13',
    'description' => 'RIDE LONDON FREE CYCLE 2013',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e20e25e-06bd-4027-ab22-cf81dfb1ad41',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EE',
    'description' => 'End to End',
    'format' => NULL,
    'weight' => 0,
    'uuid' => '9e782587-e4a5-41b7-acea-134211bb7723',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWX07',
    'description' => 'TFGM',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a033a7d9-3be5-449e-97f4-ceca126f0f1a',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RBP',
    'description' => 'Renewal by Phone',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a46d6953-d2fe-4004-98e4-e3c1b1eda03a',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CDOI',
    'description' => 'Campaign Donation (Over Internet)',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a51ccaed-517a-48e0-ba35-431811170f78',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LEGAL',
    'description' => 'Member with Legal Aid Case',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a78b7333-d192-45c4-9f2d-39f0f1097fb6',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LAPSLE',
    'description' => 'Lapse Members Follow Up - Letter',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a7a1acd1-ccd3-4762-bc41-5418ba99f699',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LAPSEM',
    'description' => 'Lapse Member Follow Up - Email',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a7c2a210-d80f-40fb-8c88-9b8a3cb5ad70',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'DOI',
    'description' => 'Donation (Over Internet)',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a9f770c8-01f1-4307-8fe7-f62703626eba',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET2404',
    'description' => 'Ret2404',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ae82913a-40d8-46f7-94d4-95f15baa32bf',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'BIKEEVENTS',
    'description' => 'Bike Events brochure advert',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'afe6f3eb-729f-4477-b9f7-4ac3b35e76c5',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'GIFT',
    'description' => 'Membership with free gift',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b1e87a9e-55dc-46d2-8794-42cc397c6501',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LSET25',
    'description' => 'Xmas gift membership 2014',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b3fb0c11-ae68-4727-ab57-d6d0d488e8fc',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CW',
    'description' => 'Cycling weekly general',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b4ebbb03-ac90-4af0-abcb-337c4e571ef2',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CTMAG17',
    'description' => 'Cycle Traveller Magazine 2017 - annual - 14 for 12 on DDM',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b5080b3c-f747-4be2-8062-879abdb7a596',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'TID',
    'description' => 'Tidworth Bike Park',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b6534ff2-d210-44f9-af75-868909d37dc2',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CTMAINT',
    'description' => 'CTC Maintenance Course',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b67e40cd-8477-4d0a-a4b6-cc1fb687fb8d',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EASQ01',
    'description' => 'CTC Leicester',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b6bf7fb4-131e-4dc1-a31f-91c6abeb98d2',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EASK04',
    'description' => 'Active Essex',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b70faf6f-daf0-4833-9f61-0a305e5af8d5',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LRS1512',
    'description' => 'Lasped Reset 15 for 12',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b8ca4afc-59f4-4269-bc2c-5b8172dad14d',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CCLIP',
    'description' => 'Cycle Clips',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b9954d9f-11e1-4ff8-b21a-cc26d0b05b3c',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RADAR',
    'description' => 'Bike Radar',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba9605e8-affc-41a6-b16a-fb54aba85c20',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'ROG',
    'description' => 'Rogate Forest',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ba9f05db-b8d0-4d43-9304-428e55d55901',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'TIL',
    'description' => 'Tilgate Forest',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bc02ecaf-78cf-4638-a638-02fd163b49f6',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'Monthly',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'be5c26b9-9713-4a44-b09f-2e4e44b5b2c8',
    'vocabulary_machine_name' => 'payment_frequencies',
    'field_code' => array(
      'und' => array(
        0 => array(
          'value' => 'M',
          'format' => NULL,
        ),
      ),
    ),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWA10',
    'description' => 'Belles, Bikes & Babies',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'bfd676cb-7600-45e6-9171-4d5e670aa99b',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LOVE2RIDE',
    'description' => 'Love to Ride Free of Charge Memberships',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c02d1d16-23ef-437e-a0ba-bb6f858ee099',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'WHATMTB',
    'description' => 'What MTB',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c40c3375-ca8c-400f-a3b7-1d9848d78d20',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'SOUC02',
    'description' => 'Hampshire CC',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c5563bf9-1db3-429f-9984-9101e1eec6f6',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EASK02',
    'description' => 'Hampshire STTY',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c6e64245-daad-41ec-91f8-915b5102faa8',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'GLA',
    'description' => 'summer membership offer - glasses',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'c9d1bc2d-9aca-41a9-8af5-5890d37df9bb',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EASK06',
    'description' => 'Essex-Women Time',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cc48457c-ce6b-4ee9-990c-db72c2663dc5',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CWE',
    'description' => 'An existing Cyclists Welcome subsciber',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cce838bf-64bd-47f0-8d7b-c3b67d59a375',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET2704',
    'description' => 'Ret2704',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'cdc17446-87df-4a82-85b6-61fe22bdb65a',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'ATMAG',
    'description' => 'Adventure Travel Magazine',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ce6d71b0-61ac-41b6-876a-8c8553a431f4',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'TG17',
    'description' => 'Imm. Media TDF Guide 2017 Advert - promotes 14 for 12',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd0c43788-9176-4ddb-b143-3c0ad22977d4',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'FORCES',
    'description' => 'Armed forces discount',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd168ea52-33a8-4c32-8823-369cc8a31a20',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWW05',
    'description' => 'Dream Fund (Play on Pedals)',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd1c3d680-d99d-4643-bf0f-019e67b0239f',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'Annually',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 1,
    'uuid' => 'd2107343-65d3-4c3b-b1ab-daea536ada18',
    'vocabulary_machine_name' => 'payment_frequencies',
    'field_code' => array(
      'und' => array(
        0 => array(
          'value' => 'A',
          'format' => NULL,
        ),
      ),
    ),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET0105',
    'description' => 'RET0105',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd21c98a1-9da6-441e-9542-0847276e1656',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWL02',
    'description' => 'NW Inclusive Cycling',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd32a854a-2255-4c2a-a9ab-57266fd322b3',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'DL',
    'description' => 'Donation',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'd76c6117-4259-4650-88c3-439eed5ca906',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'BW2015',
    'description' => 'Bike Week 2015 1 year free membership for prizewinners',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dc6c7b1f-8084-4c10-882f-80e1bb15daff',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET0405',
    'description' => 'RET0405',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dd2eeb5e-f627-4dbe-a80c-e925e552a321',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET2804',
    'description' => 'Ret2804',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dd8ca73f-b4e2-4949-8a9f-dbec160ad5fc',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CCM15',
    'description' => 'Cycle Commuter Mag Advert SpringSummer15 -15mths for 12',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'df14dcc2-1e77-4dd5-bf64-c706a8883e1b',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET0205',
    'description' => 'RET0205',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'df4248c4-5bd1-4a5f-96d1-7a7707f0d905',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RCW',
    'description' => 'Returning as a subscriber to Cyclists Welcome',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e1225968-6645-4689-9dba-9fb6cd7f36a9',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'ACTIVE',
    'description' => 'Cycling Active',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e4999b56-0629-4206-a3eb-73c3930d6327',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'LBS17ATS',
    'description' => 'London Bike Show 2017 - given KTV2 lights at show',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e4c30929-2117-466f-b007-824e5d0b10ca',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'CTOFF',
    'description' => 'CTC Offroad Training Course',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e6929fa9-1bb3-437b-a2d5-5d45853dab7f',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'SFC',
    'description' => 'Space for Cycling',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e8504e44-517b-4699-a138-bae486fe7bce',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NMP',
    'description' => 'New Member via Phone',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e9646029-5979-40e1-99e4-9b6b690fc1ef',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EASL03',
    'description' => 'SW Inclusive Cycling',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'eab2b546-f661-414d-a137-9655a7700c2b',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'OF2015',
    'description' => 'Advert in Outdoor Fitness Magazine',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ebaad3d1-0882-4498-b7ce-b2cc9513822a',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'BBR',
    'description' => 'Big Bike Revival',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'ef41b17e-0cf3-4bbe-9cfa-b3444dbdeda6',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RET0305',
    'description' => 'RET0305',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f13e5a23-81e6-4bdb-bef9-a9a12d2e3d1f',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'BCQ',
    'description' => 'BCQ request for information',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f182bd54-470a-4d3b-bfeb-1fba317b136c',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'C',
    'description' => 'Complaint',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f1d00b82-7143-4e2c-8bcd-48e92abdca59',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'PACK17',
    'description' => 'Valentine\'s Day Gift Membership 2017 - free Essentials Pack',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f260a238-b38b-4302-bbdb-5ec8d96bc401',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'PHONE',
    'description' => 'Created via Phone',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f308473a-fa07-4e15-a287-a9fa8fbe42c9',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'NOWX03',
    'description' => 'Lancashire CC',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f32c7a94-3fe4-41c0-9c9f-cade22aea232',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'YBS13',
    'description' => 'Yorkshire Bicycle Show',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f4bbc334-d0b3-47a6-a851-9cd09e1eece6',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'EN14',
    'description' => 'English Heritage 2014',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f9bc3036-bd41-4f14-a65d-c3f19991efac',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'RIDELON14',
    'description' => 'Ride London 2014 (registration inc DPA statement)',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fcebd077-3d6a-4bd0-ae1e-8d94ac8a04a0',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  $terms[] = array(
    'name' => 'MGMJOHN',
    'description' => 'Free Dave Walker Mug Jon Snow video',
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'fd747237-b371-48b8-baff-8c3338163adb',
    'vocabulary_machine_name' => 'care_fields_promotion_code',
    'field_code' => array(),
    'status' => 1,
  );
  return $terms;
}
