<?php

/**
 * @file
 * Code for the media_skyfish module.
 */

module_load_include('inc', 'media_skyfish', 'includes/media_skyfish.variables');
module_load_include('inc', 'media_skyfish', 'includes/media_skyfish.utilities');

/**
 * Implements hook_media_browser_plugin_info().
 */
function media_skyfish_media_browser_plugin_info() {
  $info['skyfish'] = array(
    'title' => t('Skyfish'),
    'class' => 'MediaSkyfishBrowser',
    'weight' => 100,
  );

  return $info;
}

/**
 * Implements hook_menu().
 */
function media_skyfish_menu() {
  $items = array();
  $items['admin/config/media/media_skyfish'] = array(
    'title' => 'Skyfish settings',
    'description' => 'Configure required settings for Media: Skyfish.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_skyfish_settings_form'),
    'access arguments' => array('configure skyfish'),
    'file' => 'includes/media_skyfish.admin.inc',
  );

  $items['user/%user/skyfish'] = array(
    'title' => 'Skyfish settings',
    'description' => 'Configure Skyfish api settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_skyfish_user_settings_form', 1),
    'access arguments' => array('configure own skyfish'),
    'file' => 'includes/media_skyfish.user.inc',
  );

  $items['skyfish/browsebydir/%'] = array(
    'page callback' => 'media_skyfish_browsebydir',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'file' => 'includes/media_skyfish.utilities.inc',
  );

  $items['skyfish/search/%'] = array(
    'page callback' => 'media_skyfish_search',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'file' => 'includes/media_skyfish.utilities.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function media_skyfish_permission() {
  return array(
    'configure skyfish' => array(
      'title' => t('Configure Global Media Skyfish settings'),
    ),
    'configure own skyfish' => array(
      'title' => t('Configure own Media Skyfish settings'),
    ),
  );
}


/*
 * Implements hook_theme().
 */
function media_skyfish_theme() {
  return array(
    'skyfish_pager' => array(
      'template' => 'skyfish-pager',
      'variables' => array('pages' => NULL, 'current' => NULL, 'dir_id' => NULL),
    ),
  );
}
