<?php
/**
 * @file
 * content_type_group_emails.features.og_features_permission.inc
 */

/**
 * Implements hook_og_features_default_permissions().
 */
function content_type_group_emails_og_features_default_permissions() {
  $permissions = array();

  // Exported og permission: 'node:affiliated_centre:create rider content'
  $permissions['node:affiliated_centre:create rider content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:delete any group_email content'
  $permissions['node:affiliated_centre:delete any group_email content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:delete any rider content'
  $permissions['node:affiliated_centre:delete any rider content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:delete own group_email content'
  $permissions['node:affiliated_centre:delete own group_email content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:delete own rider content'
  $permissions['node:affiliated_centre:delete own rider content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update any group_email content'
  $permissions['node:affiliated_centre:update any group_email content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update any rider content'
  $permissions['node:affiliated_centre:update any rider content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_active field'
  $permissions['node:affiliated_centre:update field_active field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_email_audience field'
  $permissions['node:affiliated_centre:update field_email_audience field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_email_footer field'
  $permissions['node:affiliated_centre:update field_email_footer field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_email_status field'
  $permissions['node:affiliated_centre:update field_email_status field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_email_suppression field'
  $permissions['node:affiliated_centre:update field_email_suppression field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_group_email_subscriber field'
  $permissions['node:affiliated_centre:update field_group_email_subscriber field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_group_newsletter_subscribe field'
  $permissions['node:affiliated_centre:update field_group_newsletter_subscribe field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_ice_name field'
  $permissions['node:affiliated_centre:update field_ice_name field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_ice_notes field'
  $permissions['node:affiliated_centre:update field_ice_notes field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_ice_phone_number field'
  $permissions['node:affiliated_centre:update field_ice_phone_number field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_membership_type field'
  $permissions['node:affiliated_centre:update field_membership_type field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_organisation_number field'
  $permissions['node:affiliated_centre:update field_organisation_number field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_postal_suppression field'
  $permissions['node:affiliated_centre:update field_postal_suppression field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_renewal_date field'
  $permissions['node:affiliated_centre:update field_renewal_date field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_reply_to_email_address field'
  $permissions['node:affiliated_centre:update field_reply_to_email_address field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_address_1 field'
  $permissions['node:affiliated_centre:update field_rider_address_1 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_address_2 field'
  $permissions['node:affiliated_centre:update field_rider_address_2 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_address_3 field'
  $permissions['node:affiliated_centre:update field_rider_address_3 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_contact_number field'
  $permissions['node:affiliated_centre:update field_rider_contact_number field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_country field'
  $permissions['node:affiliated_centre:update field_rider_country field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_county field'
  $permissions['node:affiliated_centre:update field_rider_county field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_email field'
  $permissions['node:affiliated_centre:update field_rider_email field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_email_suppression field'
  $permissions['node:affiliated_centre:update field_rider_email_suppression field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_forename field'
  $permissions['node:affiliated_centre:update field_rider_forename field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_joined_date field'
  $permissions['node:affiliated_centre:update field_rider_joined_date field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_notes field'
  $permissions['node:affiliated_centre:update field_rider_notes field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_postcode field'
  $permissions['node:affiliated_centre:update field_rider_postcode field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_renewal_date field'
  $permissions['node:affiliated_centre:update field_rider_renewal_date field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_salutation field'
  $permissions['node:affiliated_centre:update field_rider_salutation field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_status field'
  $permissions['node:affiliated_centre:update field_rider_status field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_surname field'
  $permissions['node:affiliated_centre:update field_rider_surname field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_rider_town field'
  $permissions['node:affiliated_centre:update field_rider_town field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_show_on_latest_feed field'
  $permissions['node:affiliated_centre:update field_show_on_latest_feed field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_voting_rights field'
  $permissions['node:affiliated_centre:update field_voting_rights field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update field_welcome_email_sent field'
  $permissions['node:affiliated_centre:update field_welcome_email_sent field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update own group_email content'
  $permissions['node:affiliated_centre:update own group_email content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:update own rider content'
  $permissions['node:affiliated_centre:update own rider content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_active field'
  $permissions['node:affiliated_centre:view field_active field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_email_audience field'
  $permissions['node:affiliated_centre:view field_email_audience field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_email_footer field'
  $permissions['node:affiliated_centre:view field_email_footer field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_email_status field'
  $permissions['node:affiliated_centre:view field_email_status field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_email_suppression field'
  $permissions['node:affiliated_centre:view field_email_suppression field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_group_email_subscriber field'
  $permissions['node:affiliated_centre:view field_group_email_subscriber field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_group_newsletter_subscribe field'
  $permissions['node:affiliated_centre:view field_group_newsletter_subscribe field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_ice_name field'
  $permissions['node:affiliated_centre:view field_ice_name field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_ice_notes field'
  $permissions['node:affiliated_centre:view field_ice_notes field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_ice_phone_number field'
  $permissions['node:affiliated_centre:view field_ice_phone_number field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_membership_type field'
  $permissions['node:affiliated_centre:view field_membership_type field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_organisation_number field'
  $permissions['node:affiliated_centre:view field_organisation_number field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_postal_suppression field'
  $permissions['node:affiliated_centre:view field_postal_suppression field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_renewal_date field'
  $permissions['node:affiliated_centre:view field_renewal_date field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_reply_to_email_address field'
  $permissions['node:affiliated_centre:view field_reply_to_email_address field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_address_1 field'
  $permissions['node:affiliated_centre:view field_rider_address_1 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_address_2 field'
  $permissions['node:affiliated_centre:view field_rider_address_2 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_address_3 field'
  $permissions['node:affiliated_centre:view field_rider_address_3 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_contact_number field'
  $permissions['node:affiliated_centre:view field_rider_contact_number field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_country field'
  $permissions['node:affiliated_centre:view field_rider_country field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_county field'
  $permissions['node:affiliated_centre:view field_rider_county field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_email field'
  $permissions['node:affiliated_centre:view field_rider_email field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_email_suppression field'
  $permissions['node:affiliated_centre:view field_rider_email_suppression field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_forename field'
  $permissions['node:affiliated_centre:view field_rider_forename field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_joined_date field'
  $permissions['node:affiliated_centre:view field_rider_joined_date field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_notes field'
  $permissions['node:affiliated_centre:view field_rider_notes field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_postcode field'
  $permissions['node:affiliated_centre:view field_rider_postcode field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_renewal_date field'
  $permissions['node:affiliated_centre:view field_rider_renewal_date field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_salutation field'
  $permissions['node:affiliated_centre:view field_rider_salutation field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_status field'
  $permissions['node:affiliated_centre:view field_rider_status field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_surname field'
  $permissions['node:affiliated_centre:view field_rider_surname field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_rider_town field'
  $permissions['node:affiliated_centre:view field_rider_town field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_show_on_latest_feed field'
  $permissions['node:affiliated_centre:view field_show_on_latest_feed field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_voting_rights field'
  $permissions['node:affiliated_centre:view field_voting_rights field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:affiliated_centre:view field_welcome_email_sent field'
  $permissions['node:affiliated_centre:view field_welcome_email_sent field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:create group_email content'
  $permissions['node:group:create group_email content'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:create rider content'
  $permissions['node:group:create rider content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:delete any group_email content'
  $permissions['node:group:delete any group_email content'] = array(
    'roles' => array(
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
    ),
  );

  // Exported og permission: 'node:group:delete any rider content'
  $permissions['node:group:delete any rider content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:delete own group_email content'
  $permissions['node:group:delete own group_email content'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:delete own rider content'
  $permissions['node:group:delete own rider content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update any group_email content'
  $permissions['node:group:update any group_email content'] = array(
    'roles' => array(
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
    ),
  );

  // Exported og permission: 'node:group:update any rider content'
  $permissions['node:group:update any rider content'] = array(
    'roles' => array(
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:update field_email_audience field'
  $permissions['node:group:update field_email_audience field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
    ),
  );

  // Exported og permission: 'node:group:update field_email_footer field'
  $permissions['node:group:update field_email_footer field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
    ),
  );

  // Exported og permission: 'node:group:update field_email_status field'
  $permissions['node:group:update field_email_status field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
    ),
  );

  // Exported og permission: 'node:group:update field_email_suppression field'
  $permissions['node:group:update field_email_suppression field'] = array(
    'roles' => array(
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:update field_ice_name field'
  $permissions['node:group:update field_ice_name field'] = array(
    'roles' => array(
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:update field_ice_notes field'
  $permissions['node:group:update field_ice_notes field'] = array(
    'roles' => array(
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:update field_ice_phone_number field'
  $permissions['node:group:update field_ice_phone_number field'] = array(
    'roles' => array(
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:update field_membership_type field'
  $permissions['node:group:update field_membership_type field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_organisation_number field'
  $permissions['node:group:update field_organisation_number field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_postal_suppression field'
  $permissions['node:group:update field_postal_suppression field'] = array(
    'roles' => array(
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:update field_renewal_date field'
  $permissions['node:group:update field_renewal_date field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_reply_to_email_address field'
  $permissions['node:group:update field_reply_to_email_address field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:update field_rider_address_1 field'
  $permissions['node:group:update field_rider_address_1 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_address_2 field'
  $permissions['node:group:update field_rider_address_2 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_address_3 field'
  $permissions['node:group:update field_rider_address_3 field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_contact_number field'
  $permissions['node:group:update field_rider_contact_number field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_country field'
  $permissions['node:group:update field_rider_country field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_county field'
  $permissions['node:group:update field_rider_county field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_email field'
  $permissions['node:group:update field_rider_email field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_email_suppression field'
  $permissions['node:group:update field_rider_email_suppression field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_forename field'
  $permissions['node:group:update field_rider_forename field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_joined_date field'
  $permissions['node:group:update field_rider_joined_date field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_notes field'
  $permissions['node:group:update field_rider_notes field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:update field_rider_postcode field'
  $permissions['node:group:update field_rider_postcode field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_renewal_date field'
  $permissions['node:group:update field_rider_renewal_date field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_salutation field'
  $permissions['node:group:update field_rider_salutation field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_status field'
  $permissions['node:group:update field_rider_status field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_surname field'
  $permissions['node:group:update field_rider_surname field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_rider_town field'
  $permissions['node:group:update field_rider_town field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_show_on_latest_feed field'
  $permissions['node:group:update field_show_on_latest_feed field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:update field_voting_rights field'
  $permissions['node:group:update field_voting_rights field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update field_welcome_email_sent field'
  $permissions['node:group:update field_welcome_email_sent field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:update own group_email content'
  $permissions['node:group:update own group_email content'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:update own rider content'
  $permissions['node:group:update own rider content'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:view field_active field'
  $permissions['node:group:view field_active field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_email_audience field'
  $permissions['node:group:view field_email_audience field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
    ),
  );

  // Exported og permission: 'node:group:view field_email_footer field'
  $permissions['node:group:view field_email_footer field'] = array(
    'roles' => array(
      'member' => 'member',
      'non-member' => 'non-member',
    ),
  );

  // Exported og permission: 'node:group:view field_email_status field'
  $permissions['node:group:view field_email_status field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
    ),
  );

  // Exported og permission: 'node:group:view field_email_suppression field'
  $permissions['node:group:view field_email_suppression field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_group_email_subscriber field'
  $permissions['node:group:view field_group_email_subscriber field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_group_newsletter_subscribe field'
  $permissions['node:group:view field_group_newsletter_subscribe field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_ice_name field'
  $permissions['node:group:view field_ice_name field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_ice_notes field'
  $permissions['node:group:view field_ice_notes field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_ice_phone_number field'
  $permissions['node:group:view field_ice_phone_number field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_membership_type field'
  $permissions['node:group:view field_membership_type field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_organisation_number field'
  $permissions['node:group:view field_organisation_number field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:view field_postal_suppression field'
  $permissions['node:group:view field_postal_suppression field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_renewal_date field'
  $permissions['node:group:view field_renewal_date field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:view field_reply_to_email_address field'
  $permissions['node:group:view field_reply_to_email_address field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_address_1 field'
  $permissions['node:group:view field_rider_address_1 field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_address_2 field'
  $permissions['node:group:view field_rider_address_2 field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_address_3 field'
  $permissions['node:group:view field_rider_address_3 field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_contact_number field'
  $permissions['node:group:view field_rider_contact_number field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_country field'
  $permissions['node:group:view field_rider_country field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_county field'
  $permissions['node:group:view field_rider_county field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_email field'
  $permissions['node:group:view field_rider_email field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_email_suppression field'
  $permissions['node:group:view field_rider_email_suppression field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_forename field'
  $permissions['node:group:view field_rider_forename field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_joined_date field'
  $permissions['node:group:view field_rider_joined_date field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_notes field'
  $permissions['node:group:view field_rider_notes field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_postcode field'
  $permissions['node:group:view field_rider_postcode field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_renewal_date field'
  $permissions['node:group:view field_rider_renewal_date field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_salutation field'
  $permissions['node:group:view field_rider_salutation field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_status field'
  $permissions['node:group:view field_rider_status field'] = array(
    'roles' => array(),
  );

  // Exported og permission: 'node:group:view field_rider_surname field'
  $permissions['node:group:view field_rider_surname field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_rider_town field'
  $permissions['node:group:view field_rider_town field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_show_on_latest_feed field'
  $permissions['node:group:view field_show_on_latest_feed field'] = array(
    'roles' => array(
      'Email Editor (Member Groups Only - Beta)' => 'Email Editor (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_voting_rights field'
  $permissions['node:group:view field_voting_rights field'] = array(
    'roles' => array(
      'Group Administrator' => 'Group Administrator',
      'Group Manager (automatically assigned)' => 'Group Manager (automatically assigned)',
      'Registration Officer (Member Groups Only - Beta)' => 'Registration Officer (Member Groups Only - Beta)',
    ),
  );

  // Exported og permission: 'node:group:view field_welcome_email_sent field'
  $permissions['node:group:view field_welcome_email_sent field'] = array(
    'roles' => array(),
  );

  return $permissions;
}
